### ISSUE TITLE
Address new ACTIVITY_RECOGNITION Android permission

### ISSUE THREAD

**Issue by VladKozlov368** [dariosalvi78/cordova-plugin-health#178]
There was a problem that on some devices we can't receive data from Google Fit. For example, in Xiaomi Mi 8, android 10, we always get the error `com.google.step_count.delta requires android.permission.activity_recognition`. All stages of authorization have been completed and permissions have been given everywhere to receive data: `['steps', 'weight', 'blood_pressure', 'heart_rate']`. In `config.xml` are written: `HEALTH_READ_PERMISSION`, `HEALTH_WRITE_PERMISSION`

_But this error is rarely shown, and on many devices, after authorization, we can correctly get the data._

**Has anyone encountered this problem?**

**Comment by dariosalvi78** [comment]
looks like [something new introduce by Android 10](https://developer.android.com/about/versions/10/privacy/changes). The  permission is  automatically granted if you target Android 9 or lower, which may fix it temporarily. For future  implementations, it would be better to include this when requesting permissions for [these specific data sets](https://developers.google.com/fit/android/authorization#data_types_that_need_android_permissions).

Very happy to receive PRs in this regard.

**Comment by VladKozlov368** [comment]
@dariosalvi78 yes it works for me, thanks!

### For 10 android need to do the following:

**step 1:** add plugin android permissions
```
ionic cordova plugin add cordova-plugin-android-permissions
npm install @ionic-native/android-permissions
```
**step 2:** go to the config.xml file in the root folder and add:
```
<platform name="android">
    ...
    <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/uses-permission" xmlns:android="http://schemas.android.com/apk/res/android">
        ...
        <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    </edit-config>
</platform>
```

**step 3:** request permissions ACTIVITY_RECOGNITION and then perform the necessary actions...
```
constructor(private _androidPermissions: AndroidPermissions) {
    this._androidPermissions.requestPermission('android.permission.ACTIVITY_RECOGNITION')
        .then(result => {
            console.log(result.hasPermission);
            // Authorize using the requestAuthorization method in health plugin
        })
        .catch(console.error);
}
```

**Comment by dariosalvi78** [comment]
I want to keep this open as the solution should be included in the plugin.

**Comment by gasci** [comment]
Great plugin! Has the problem with steps regarding the Android 10 permission been solved?

**Comment by dariosalvi78** [comment]
I've been going through this: the current cordova [android support ](https://cordova.apache.org/docs/en/latest/guide/platforms/android/)targets API version up to 28 (Android 9). This makes it impossible to use the new permissions on a regular cordova project. How did you get into this problem?

**Comment by gasci** [comment]
You can find the relevant info here: https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html

Google forces 29 as the minimum target API.
________________________________

**Comment by gasci** [comment]
preference name="android-targetSdkVersion" value="29"
________________________________

**Comment by gasci** [comment]
GH-848<https://github.com/apache/cordova-android/pull/848> breaking: increased default target sdk to 29 this is an update of cordova-android 9.0.0
________________________________

**Comment by dariosalvi78** [comment]
this should be solved now. I haven't tested this thoroughly, so, before releasing a new version, I would appreciate a confirmation that this is working in your app(s). Please be aware that I have removed DOB and gender from Fit (didn't make sense) and that you will need to activate AndroidX if you use the latest Android platform (see README for that).

**Comment by gasci** [comment]
How do we install it without being released with your latest commit?
________________________________

**Comment by gasci** [comment]
Physical activity permission works but body sensor permission is still missing.
________________________________

**Comment by dariosalvi78** [comment]
what data type are you trying to access concretely?

**Comment by gasci** [comment]
["distance", "calories", "steps"] this is my array.
________________________________

**Comment by dariosalvi78** [comment]
I have tested distance, calories and steps independently and they are working on my phone. I have found a little bug anyway so I recommend you pull the latest version and try again.
For faster communication, I would suggest using the [official chat](https://gitter.im/cordova-plugin-health/Lobby).
