### ISSUE TITLE
Build issue with new version

### ISSUE THREAD

**Issue by dlandtaa** [dariosalvi78/cordova-plugin-health#265]
I just updated my app to the new version `2.0.4` (thank you for releasing that) but I'm getting a few issues with the builds.

On iOS I'm seeing three errors inside `HealthKit.m`:
```
414: Use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepCore'; did you mean 'HKCategoryValueSleepAnalysisAsleep'?
415: Use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepDeep'; did you mean 'HKCategoryValueSleepAnalysisAsleep'?
416: Use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepREM'; did you mean 'HKCategoryValueSleepAnalysisAsleep'?
```

Likewise I'm getting some issues with the Android build inside `HealthKit.java`:

```
/my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:667: error: cannot find symbol
          else if (datapoint.getValue(FIELD_OXYGEN_SATURATION_AVERAGE) != null)
                                      ^
  symbol:   variable FIELD_OXYGEN_SATURATION_AVERAGE
  location: class org.apache.cordova.health.HealthPlugin
/my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:668: error: cannot find symbol
            oxysat = datapoint.getValue(FIELD_OXYGEN_SATURATION_AVERAGE).asFloat();
                                        ^
  symbol:   variable FIELD_OXYGEN_SATURATION_AVERAGE
  location: class org.apache.cordova.health.HealthPlugin
/my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:673: error: cannot find symbol
          if (datapoint.getValue(FIELD_OXYGEN_SATURATION_MAX) != null)
                                 ^
  symbol:   variable FIELD_OXYGEN_SATURATION_MAX
  location: class org.apache.cordova.health.HealthPlugin
/my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:674: error: cannot find symbol
            obj.put("max", datapoint.getValue(FIELD_OXYGEN_SATURATION_MAX).asFloat());
                                              ^
  symbol:   variable FIELD_OXYGEN_SATURATION_MAX
  location: class org.apache.cordova.health.HealthPlugin
/my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:675: error: cannot find symbol
          if (datapoint.getValue(FIELD_OXYGEN_SATURATION_MIN) != null)
                                 ^
  symbol:   variable FIELD_OXYGEN_SATURATION_MIN
  location: class org.apache.cordova.health.HealthPlugin
/my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:676: error: cannot find symbol
            obj.put("min", datapoint.getValue(FIELD_OXYGEN_SATURATION_MIN).asFloat());
                                              ^
  symbol:   variable FIELD_OXYGEN_SATURATION_MIN
  location: class org.apache.cordova.health.HealthPlugin
Note: /my-app/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors
```

**Comment by dariosalvi78** [comment]
mmm, I'll need to test this myself.
which versions of cordova-ios and cordova-android are you using?

**Comment by nielsjakob** [comment]
I am getting the same errors in Android Studio (2021.3.1) for 2.0.4 (2.0.0 works fine if I downgrade). I'm using Android@11.0.0 with SDK Version 32 and Android Gradle Plugin Version 7.3.0

**Comment by dlandtaa** [comment]
Here are all the versions:
```
$ cordova info

Cordova Packages:

    cli: 11.0.0
        common: 4.0.2
        create: 4.0.0
        lib: 11.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

    android: 9.1.0
    ios: 6.2.0

Environment:

    OS: macOS Monterey 12.4 (21F79) (darwin 21.5.0) x64
    Node: v16.16.0
    npm: 8.11.0

android Environment:

    android:
ERROR: Command failed with ENOENT: avdmanager list target
spawn avdmanager ENOENT

ios Environment:

    xcodebuild:
Xcode 13.4.1
Build version 13F100
```

**Comment by dariosalvi78** [comment]
I have fixed the bug on Android, but the iOS part seems to compile here. See new release (2.0.5).
Tested with cordova-android 10.1.2, and cordova-ios 6.2.0.

**Comment by scattered** [comment]
I know this issue is closed, but I'm having the exact same issue with release `2.0.5` using `cordova-ios: 6.2.0`.

My `cordova info` response is the same as @dlandtaa above, so not sure what the issue could be. My Android build using `cordova-android: 10.1.2` (minSDK: 19, targetSDK: 31) works fine.

The only thing I can think of is that my iOS deployment-target (I've tried 11, 12 and 13) or project format (I've tried 11.0, 11.4, 12.0 and 13.0) might be wrong?

To provide more detail, I'm using `"cordova-plugin-health": "github:dariosalvi78/cordova-plugin-health"` in my package.json

I also have the following settings in `cordova.plugins` (within package.json):

```
"cordova-plugin-health": {
  "HEALTH_READ_PERMISSION": "This allows MyVision by VisionPT to read data from Health.",
  "HEALTH_WRITE_PERMISSION": "This allows MyVision by VisionPT to write data to Health.",
  "FIT_API_VERSION": "20.0.0",
  "PLAY_AUTH_VERSION": "19.0.0"
},
```

Is any of the above wrong or misconfigured? Any advice on resolving this issue would be greatly appreciated.

**Comment by dland512** [comment]
Just as an update I'm still seeing this issue. It's easily reproducible on a very basic cordova project. I just have to run

```
cordova create myproject
cd myproject
cordova plugin add cordova-plugin-health
cordova platform add ios
cordova prepare ios
```
Then opening up the project in Xcode and building it will give the errors above.

This happens on my macbook pro but I'm not on my mac mini. The main difference (from I can tell) between them is the versions of macOS and Xcode which, are newer on the mini. I'm going to try upgrading those on the macbook pro to see if that helps.
