### ISSUE TITLE
add support for distance in Android

### ISSUE THREAD

**Issue by dariosalvi78** [dariosalvi78/cordova-plugin-health#313]
this was already included in the previous plugin and is available in iOS.

**Comment by maswa** [comment]
Would be greatly appreciated if we can get support for distance.  I'm trying to move away from Google Fit to Health Connect and in my app we need to fetch steps, which already works in the latest plugin, and we need it for cycling / biking distances.

**Comment by dariosalvi78** [comment]
for my reference: [distance](https://developer.android.com/reference/kotlin/androidx/health/connect/client/records/DistanceRecord).

Is [biking cadence](https://developer.android.com/reference/kotlin/androidx/health/connect/client/records/CyclingPedalingCadenceRecord) of interest for your app too?

**Comment by dariosalvi78** [comment]
fixed in 3.0.3

**Comment by maswa** [comment]
Hello Dario, 

Thanks for adding distance support for activities in the plugin.  However I have read your readme doc many times and tried in several ways but I’m still not able to get the distances in my activities it is still only giving me the time in ms for , I do not get the distance in m. 



I’m using the query that I have been using with your version 2 plugin and which worked fine with Google Fit and Apple Health.  Of course I have changed the datatypes object as mentioned in your readme file and  also i have permissions for 
<uses-permission android:name="android.permission.health.READ_EXERCISE" />
<uses-permission android:name="android.permission.health.READ_STEPS" />
<uses-permission android:name="android.permission.health.READ_DISTANCE" />

Google has already approved usage of these permissions in our app 2 weeks ago, so that is no issue either. 



I have added the flag includeDistance also.  So I’m not sure if I’m still missing something to be able to get the distance in the Health data. 

For your reference here is my current query : 


          cordova.plugins.health.queryAggregated({
	  startDate: start_date,
          endDate: end_date,
          dataType: op_type,
          includeDistance: true, // Cruciaal voor het ophalen van afstandsgegevens
          bucket: "day",
          filtered: true,
        }, health_read_success_aggregated, function(err) {
          show_alert("Error", err, "OK");
        });

op_type is “activity”  for this case. 

And then it gives me :  "Aggregated Data: [{"startDate":"2024-02-10T23:00:00.000Z","endDate":"2024-02-11T23:00:00.000Z","value":1800000,"unit":"ms"}]”
So still only time in ms and not distance in m 

The rest of my code has not been changed so is still the same as used for our working implementation based on plugin version 2.1 


Do you have any clues for me how to get the distance data from Health Connect with the latest plugin version?

Thanks,

Marcel

**Comment by dariosalvi78** [comment]
Hi Marcel,

the includeCalories and includeDistance flags only work for the query method, not the queryAggregated (as documented on the Readme). I have just done yet another test myself just to be sure and I can confirm: it works on my phone.

If you want aggregated distance, just issue a separate query for that.
