### ISSUE TITLE
requestAuthorization error on Android

### ISSUE THREAD

**Issue by consciousness123** [dariosalvi78/cordova-plugin-health#34]
When I tried to use requestAuthorization function on Android 5.1, i got "Invalid Action" error.

**Comment by dariosalvi78** [comment]
try reverting back to the previous version, I might have introduced a bug in the latest commits but I won't be able to solve it until beginning of January. Let me know if that solved it.

**Comment by dariosalvi78** [comment]
Ok I've found the mistake, let me know if it's fixed now...

**Comment by consciousness123** [comment]
The bug is not fixed. I got the same error on Android. IOS works well

**Comment by dariosalvi78** [comment]
You'll need to use the previous version for now, at least until I'll be able to work on it again in January.

**Comment by tylervz5** [comment]
@dariosalvi78 [this commit](https://github.com/dariosalvi78/cordova-plugin-health/commit/b1f1276803b225cf259ac64d2c685f139639c696) fixed the issue for me. Thank you!

**Comment by dariosalviwork** [comment]
I've checked and it works now
